[package]
name = "core"
version = "1.0.0"

[addresses]
supra_oracle = "0xbf06f1338594a25e52202265c741864bc88093043a6a74e5ff52845a41983db0"


[dependencies.SupraFramework]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
rev = "dev"
subdir = "aptos-move/framework/supra-framework"

